import {
  Award,
  Briefcase,
  Building2,
  Car,
  Compass,
  Crown,
  FileCheck,
  Globe2,
  GraduationCap,
  Headphones,
  Map,
  PenLine,
  Plane,
  PlaneTakeoff,
  Plus,
  Route,
  ShieldCheck,
  Ship,
  Sparkles,
  User,
  Users,
  Zap,
  Clock,
  CalendarCheck,
  BadgeCheck,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  compass: Compass,
  "pen-line": PenLine,
  penline: PenLine,
  sparkles: Sparkles,
  plane: Plane,
  "plane-takeoff": PlaneTakeoff,
  planetakeoff: PlaneTakeoff,
  award: Award,
  headphones: Headphones,
  globe2: Globe2,
  globe: Globe2,
  user: User,
  users: Users,
  map: Map,
  route: Route,
  plus: Plus,
  zap: Zap,
  "shield-check": ShieldCheck,
  shieldcheck: ShieldCheck,
  "file-check": FileCheck,
  filecheck: FileCheck,
  ship: Ship,
  car: Car,
  crown: Crown,
  "graduation-cap": GraduationCap,
  graduationcap: GraduationCap,
  briefcase: Briefcase,
  "building-2": Building2,
  building2: Building2,
  clock: Clock,
  "calendar-check": CalendarCheck,
  calendarcheck: CalendarCheck,
  "badge-check": BadgeCheck,
  badgecheck: BadgeCheck,
};

export function iconFromKey(key: string | undefined | null, fallback: LucideIcon = Sparkles): LucideIcon {
  if (!key) return fallback;
  const normalized = key.trim().toLowerCase().replace(/_/g, "-");
  return ICON_MAP[normalized] ?? ICON_MAP[normalized.replace(/-/g, "")] ?? fallback;
}
