import type { AdminEntityDef } from "@/lib/admin/types";
import { formValueToNestedList, nestedListToFormValue } from "@/lib/admin/nested-list";

const M = { endpoint: "/media", valueKey: "id", labelKeys: ["slug", "url"] };
const D = { endpoint: "/destinations", valueKey: "id", labelKey: "name" };

export const ALL_ADMIN_ENTITIES: Record<string, AdminEntityDef> = {
  "destination-categories": {
    key: "destination-categories", label: "Destination Category", pluralLabel: "Destination Categories",
    group: "catalog", endpoint: "/destination-categories", nameField: "title", hideFromNav: true,
    fields: [
      { name: "title", label: "Title", type: "text", required: true, showInList: true },
      { name: "slug", label: "Slug", type: "slug", required: true, showInList: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "sort_order", label: "Sort order", type: "number", required: true, showInList: true },
    ],
  },
  packages: {
    key: "packages", label: "Package", pluralLabel: "Packages", group: "catalog", endpoint: "/packages", nameField: "title",
    fields: [
      { name: "title", label: "Title", type: "text", required: true, showInList: true },
      { name: "slug", label: "Slug", type: "slug", required: true, showInList: true },
      { name: "destination_id", label: "Destination", type: "relation", required: true, relation: D, showInList: true, listFormat: (_v, r) => String(r.destination_name ?? "—") },
      { name: "duration_label", label: "Duration label", type: "text", required: true, showInList: true },
      { name: "rating", label: "Rating", type: "number" },
      { name: "price", label: "Price", type: "number", required: true, showInList: true, listFormat: (v) => (v === 0 || v == null ? "Inquire for price" : String(v)) },
      { name: "hero_media_id", label: "Hero media", type: "relation", relation: M },
      {
        name: "highlights",
        label: "Highlights",
        type: "nested-list",
        nestedList: "highlights",
        readFrom: (record) => nestedListToFormValue("highlights", record.highlights),
        writeValue: (value) => formValueToNestedList("highlights", value),
      },
      { name: "moods", label: "Moods", type: "tags" },
      {
        name: "is_featured",
        label: "Homepage hero slider",
        type: "boolean",
        helpText: "When enabled, this package can appear in the homepage hero slider.",
        showInList: true,
        listLabel: "Hero",
      },
      {
        name: "featured_sort_order",
        label: "Hero slider order",
        type: "number",
        helpText: "Lower numbers appear first in the homepage hero slider (1 = first).",
        showInList: true,
        listLabel: "Hero order",
      },
      { name: "is_published", label: "Published", type: "boolean" },
    ],
  },
  itineraries: {
    key: "itineraries", label: "Itinerary", pluralLabel: "Itineraries", group: "catalog", endpoint: "/itineraries", nameField: "title",
    fields: [
      { name: "title", label: "Title", type: "text", required: true, showInList: true },
      { name: "slug", label: "Slug", type: "slug", required: true, showInList: true },
      { name: "destination_id", label: "Destination", type: "relation", required: true, relation: D, showInList: true, listFormat: (_v, r) => String(r.destination_name ?? "—") },
      { name: "package_id", label: "Package", type: "relation", relation: { endpoint: "/packages", valueKey: "id", labelKey: "title" }, showInList: true, listFormat: (_v, r) => String(r.package_title ?? "—") },
      { name: "duration_label", label: "Duration label", type: "text", required: true, showInList: true },
      { name: "duration_days", label: "Duration days", type: "number", required: true },
      { name: "starting_price", label: "Starting price", type: "number", required: true, showInList: true, listFormat: (v) => (v === 0 || v == null ? "Inquire for price" : String(v)) },
      { name: "price_note", label: "Price note", type: "textarea" },
      { name: "rating", label: "Rating", type: "number" },
      { name: "review_count", label: "Review count", type: "number" },
      { name: "hero_media_id", label: "Hero media", type: "relation", relation: M },
      { name: "tagline", label: "Tagline", type: "text", required: true },
      { name: "overview", label: "Overview", type: "textarea", required: true },
      {
        name: "highlights",
        label: "Highlights",
        type: "nested-list",
        nestedList: "highlights",
        readFrom: (record) => nestedListToFormValue("highlights", record.highlights),
        writeValue: (value) => formValueToNestedList("highlights", value),
      },
      {
        name: "days",
        label: "Days",
        type: "nested-list",
        nestedList: "itineraryDays",
        readFrom: (record) => nestedListToFormValue("itineraryDays", record.days),
        writeValue: (value) => formValueToNestedList("itineraryDays", value),
      },
      {
        name: "hotels",
        label: "Hotels",
        type: "nested-list",
        nestedList: "itineraryHotels",
        readFrom: (record) => nestedListToFormValue("itineraryHotels", record.hotels),
        writeValue: (value) => formValueToNestedList("itineraryHotels", value),
      },
      {
        name: "inclusions",
        label: "Inclusions",
        type: "nested-list",
        nestedList: "inclusions",
        readFrom: (record) => nestedListToFormValue("inclusions", record.inclusions),
        writeValue: (value) => formValueToNestedList("inclusions", value),
      },
      { name: "gallery_media_ids", label: "Gallery media", type: "relation-multi", relation: M,
        readFrom: (r) => Array.isArray(r.gallery_media) ? r.gallery_media.map((m: {id:string}) => m.id) : [] },
      { name: "is_featured", label: "Featured", type: "boolean" },
      { name: "featured_sort_order", label: "Featured sort order", type: "number" },
      { name: "seo_title", label: "SEO title", type: "text" },
      { name: "seo_description", label: "SEO description", type: "textarea" },
      { name: "is_published", label: "Published", type: "boolean" },
    ],
  },
  hotels: {
    key: "hotels", label: "Hotel", pluralLabel: "Hotels", group: "catalog", endpoint: "/hotels", nameField: "name",
    fields: [
      { name: "name", label: "Name", type: "text", required: true, showInList: true },
      { name: "slug", label: "Slug", type: "slug", required: true, showInList: true },
      { name: "destination_id", label: "Destination", type: "relation", required: true, relation: D, showInList: true, listFormat: (_v, r) => String(r.destination_name ?? "—") },
      { name: "stars", label: "Stars", type: "number", required: true, showInList: true },
      { name: "price", label: "Price", type: "number", required: true, showInList: true },
      { name: "rating", label: "Rating", type: "number" },
      { name: "review_count", label: "Review count", type: "number" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "hero_media_id", label: "Hero media", type: "relation", relation: M },
      { name: "amenities", label: "Amenities", type: "tags" },
      {
        name: "nearby_attractions",
        label: "Nearby attractions",
        type: "nested-list",
        nestedList: "hotelAttractions",
        readFrom: (record) => nestedListToFormValue("hotelAttractions", record.nearby_attractions),
        writeValue: (value) => formValueToNestedList("hotelAttractions", value),
      },
      { name: "gallery_media_ids", label: "Gallery media", type: "relation-multi", relation: M,
        readFrom: (r) => Array.isArray(r.gallery_media) ? r.gallery_media.map((m: {id:string}) => m.id) : [] },
      { name: "is_published", label: "Published", type: "boolean" },
    ],
  },
  experiences: {
    key: "experiences", label: "Experience", pluralLabel: "Experiences", group: "catalog", endpoint: "/experiences", nameField: "headline",
    fields: [
      { name: "headline", label: "Headline", type: "text", required: true, showInList: true },
      { name: "slug", label: "Slug", type: "slug", required: true, showInList: true },
      { name: "eyebrow", label: "Eyebrow", type: "text", required: true },
      { name: "intro", label: "Intro", type: "textarea", required: true },
      { name: "hero_media_id", label: "Hero media", type: "relation", relation: M },
      { name: "card_number", label: "Card number", type: "text" },
      { name: "card_title", label: "Card title", type: "text" },
      { name: "card_description", label: "Card description", type: "textarea" },
      { name: "image_caption", label: "Image caption", type: "text" },
      { name: "layout", label: "Layout", type: "text" },
      { name: "variant", label: "Variant", type: "text" },
      { name: "quote", label: "Quote", type: "textarea" },
      { name: "cta_title", label: "CTA title", type: "text" },
      { name: "cta_description", label: "CTA description", type: "textarea" },
      {
        name: "offers",
        label: "Offers",
        type: "nested-list",
        nestedList: "experienceOffers",
        readFrom: (record) => nestedListToFormValue("experienceOffers", record.offers),
        writeValue: (value) => formValueToNestedList("experienceOffers", value),
      },
      {
        name: "stats",
        label: "Stats",
        type: "nested-list",
        nestedList: "experienceStats",
        readFrom: (record) => nestedListToFormValue("experienceStats", record.stats),
        writeValue: (value) => formValueToNestedList("experienceStats", value),
      },
      {
        name: "process_steps",
        label: "Process steps",
        type: "nested-list",
        nestedList: "experienceProcessSteps",
        readFrom: (record) => nestedListToFormValue("experienceProcessSteps", record.process_steps),
        writeValue: (value) => formValueToNestedList("experienceProcessSteps", value),
      },
      { name: "show_on_homepage", label: "Show on homepage", type: "boolean", showInList: true },
      { name: "homepage_sort_order", label: "Homepage sort order", type: "number" },
      { name: "is_published", label: "Published", type: "boolean" },
    ],
  },
  media: {
    key: "media", label: "Media Asset", pluralLabel: "Media Assets", group: "catalog", endpoint: "/media", nameField: "slug",
    fields: [
      { name: "url", label: "URL", type: "text", required: true, showInList: true, helpText: "Filled automatically when you upload via the media picker. External URLs are copied to the API server on save." },
      { name: "slug", label: "Slug", type: "slug", showInList: true },
      { name: "alt_text", label: "Alt text", type: "text", showInList: true },
      { name: "mime_type", label: "MIME type", type: "text" },
      { name: "width", label: "Width", type: "number" },
      { name: "height", label: "Height", type: "number" },
      { name: "source", label: "Source", type: "text", helpText: "e.g. external" },
      { name: "usage", label: "Usage tag", type: "text", showInList: true },
      { name: "tags", label: "Tags", type: "tags" },
    ],
  },
  "client-stories": {
    key: "client-stories", label: "Client Story", pluralLabel: "Client Stories", group: "content", endpoint: "/client-stories", nameField: "client_name",
    formFields: [
      "client_name",
      "destination_id",
      "quote",
      "portrait_media_id",
      "show_on_home",
      "show_in_gallery",
      "is_featured_in_gallery",
      "home_sort_order",
      "gallery_sort_order",
      "is_published",
    ],
    writableFields: [
      "client_name",
      "destination_id",
      "quote",
      "portrait_media_id",
      "show_on_home",
      "show_in_gallery",
      "is_featured_in_gallery",
      "home_sort_order",
      "gallery_sort_order",
      "is_published",
    ],
    fields: [
      { name: "client_name", label: "Client name", type: "text", required: true, showInList: true },
      { name: "destination_id", label: "Destination", type: "relation", relation: D },
      {
        name: "quote",
        label: "Review",
        type: "textarea",
        showInList: true,
        listFormat: (value) => {
          const text = String(value ?? "").trim();
          if (!text) return "—";
          return text.length > 200 ? `${text.slice(0, 200)}…` : text;
        },
      },
      { name: "portrait_media_id", label: "Media", type: "relation", relation: M, mediaUploadOnly: true },
      { name: "show_on_home", label: "Show on home", type: "boolean", showInList: true, helpText: "Legacy flag. Homepage shows the top 6 published reviews by sort order (same as Client Stories)." },
      { name: "show_in_gallery", label: "Photo grid", type: "boolean", showInList: true, helpText: "Show portrait in the client stories photo grid (when Active)." },
      { name: "is_featured_in_gallery", label: "Featured in gallery", type: "boolean" },
      { name: "home_sort_order", label: "Home sort order", type: "number", showInList: true, listLabel: "Order", helpText: "Lower numbers appear first on Client Stories and the homepage carousel (top 6)." },
      { name: "gallery_sort_order", label: "Gallery sort order", type: "number" },
      {
        name: "is_published",
        label: "Active",
        type: "boolean",
        showInList: true,
        listToggle: true,
        helpText: "Inactive by default. Turn on to show photos and reviews on the client stories page.",
      },
    ],
  },
  "gallery-categories": {
    key: "gallery-categories", label: "Gallery Category", pluralLabel: "Gallery Categories", group: "content", endpoint: "/gallery-categories", nameField: "label",
    fields: [
      { name: "label", label: "Label", type: "text", required: true, showInList: true },
      { name: "slug", label: "Slug", type: "slug", required: true, showInList: true },
      { name: "sort_order", label: "Sort order", type: "number", required: true, showInList: true },
    ],
  },
  "gallery-items": {
    key: "gallery-items", label: "Gallery Item", pluralLabel: "Gallery Items", group: "content", endpoint: "/gallery-items", nameField: "place",
    writableFields: ["place", "media_ids", "category_ids", "sort_order", "is_published"],
    fields: [
      { name: "place", label: "Name", type: "text", required: true, showInList: true, listInlineEdit: true },
      {
        name: "media_ids",
        label: "Media",
        type: "relation-multi",
        required: true,
        relation: M,
        mediaUploadOnly: true,
        readFrom: (r) =>
          Array.isArray(r.media)
            ? r.media.map((m: { id: string }) => m.id)
            : r.media_id
              ? [String(r.media_id)]
              : [],
      },
      { name: "category_ids", label: "Categories", type: "relation-multi", relation: { endpoint: "/gallery-categories", valueKey: "id", labelKey: "label" },
        readFrom: (r) => Array.isArray(r.categories) ? r.categories.map((c: {id:string}) => c.id) : [], showInList: true,
        listFormat: (_v, r) => Array.isArray(r.categories) ? r.categories.map((c: {label:string}) => c.label).join(", ") || "—" : "—" },
      { name: "sort_order", label: "Sort order", type: "number" },
      { name: "is_published", label: "Published", type: "boolean" },
    ],
  },
  faqs: {
    key: "faqs", label: "FAQ", pluralLabel: "FAQs", group: "content", endpoint: "/faqs", nameField: "question",
    fields: [
      { name: "question", label: "Question", type: "text", required: true, showInList: true },
      { name: "answer", label: "Answer", type: "textarea", required: true },
      { name: "itinerary_id", label: "Itinerary", type: "relation", relation: { endpoint: "/itineraries", valueKey: "id", labelKey: "title" } },
      { name: "sort_order", label: "Sort order", type: "number", required: true, showInList: true },
      { name: "is_published", label: "Published", type: "boolean" },
    ],
  },
  "site-settings": {
    key: "site-settings", label: "Site Settings", pluralLabel: "Site Settings", group: "site-config", endpoint: "/site-settings", isSingleton: true,
    fields: [
      { name: "phone", label: "Phone", type: "text", required: true },
      { name: "phone_href", label: "Phone href", type: "text", required: true },
      { name: "whatsapp", label: "WhatsApp", type: "text", required: true },
      { name: "whatsapp_href", label: "WhatsApp href", type: "text", required: true },
      { name: "email", label: "Email", type: "text", required: true },
      { name: "email_href", label: "Email href", type: "text", required: true },
      { name: "inquiry_email", label: "Inquiry email", type: "text", required: true },
      { name: "instagram_url", label: "Instagram URL", type: "text" },
      { name: "address", label: "Address", type: "textarea", required: true },
      { name: "hours", label: "Hours", type: "text", required: true },
      { name: "footer_tagline", label: "Footer tagline", type: "textarea", required: true },
      { name: "copyright_text", label: "Copyright text", type: "text", required: true },
      { name: "default_meta_title", label: "Default meta title", type: "text", required: true },
      { name: "default_meta_description", label: "Default meta description", type: "textarea", required: true },
      { name: "default_meta_keywords", label: "Default meta keywords", type: "tags" },
      { name: "og_title", label: "OG title", type: "text" },
      { name: "og_description", label: "OG description", type: "textarea" },
      { name: "favicon_media_id", label: "Favicon media", type: "relation", relation: M },
      { name: "icon_media_id", label: "Icon media", type: "relation", relation: M },
      { name: "apple_icon_media_id", label: "Apple icon media", type: "relation", relation: M },
      { name: "logo_media_id", label: "Logo media", type: "relation", relation: M },
    ],
  },
  "navigation-links": {
    key: "navigation-links", label: "Navigation Link", pluralLabel: "Navigation Links", group: "site-config", endpoint: "/navigation-links", nameField: "label",
    fields: [
      { name: "menu_group", label: "Menu group", type: "text", required: true, showInList: true },
      { name: "label", label: "Label", type: "text", required: true, showInList: true },
      { name: "href", label: "Href", type: "text", required: true, showInList: true },
      { name: "sort_order", label: "Sort order", type: "number", required: true, showInList: true },
      { name: "is_visible", label: "Visible", type: "boolean", showInList: true },
    ],
  },
  "site-ctas": {
    key: "site-ctas", label: "Site CTA", pluralLabel: "Site CTAs", group: "site-config", endpoint: "/site-ctas", nameField: "label",
    fields: [
      { name: "key", label: "Key", type: "slug", required: true, showInList: true },
      { name: "label", label: "Label", type: "text", required: true, showInList: true },
      { name: "href", label: "Href", type: "text", required: true, showInList: true },
      { name: "sort_order", label: "Sort order", type: "number", showInList: true },
    ],
  },
  "global-page-cta": {
    key: "global-page-cta", label: "Global Page CTA", pluralLabel: "Global Page CTA", group: "site-config", endpoint: "/global-page-cta", isSingleton: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "primary_cta_key", label: "Primary CTA", type: "relation", required: true, relation: { endpoint: "/site-ctas", valueKey: "key", labelKey: "label" } },
      { name: "secondary_cta_key", label: "Secondary CTA", type: "relation", required: true, relation: { endpoint: "/site-ctas", valueKey: "key", labelKey: "label" } },
    ],
  },
  "page-metadata": {
    key: "page-metadata", label: "Page Metadata", pluralLabel: "Page Metadata", group: "site-config", endpoint: "/page-metadata", nameField: "page_key",
    fields: [
      { name: "page_key", label: "Page key", type: "slug", required: true, showInList: true },
      { name: "title", label: "Title", type: "text", required: true, showInList: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "og_image_media_id", label: "OG image media", type: "relation", relation: M },
    ],
  },
  "page-heroes": {
    key: "page-heroes", label: "Page Hero", pluralLabel: "Page Heroes", group: "site-config", endpoint: "/page-heroes", nameField: "title",
    fields: [
      { name: "page_key", label: "Page key", type: "slug", required: true, showInList: true },
      { name: "region_variant", label: "Region variant", type: "text" },
      { name: "eyebrow", label: "Eyebrow", type: "text", required: true },
      { name: "badge", label: "Badge", type: "text" },
      { name: "title", label: "Title", type: "text", required: true, showInList: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "hero_media_id", label: "Hero media", type: "relation", relation: M },
      { name: "hero_image_alt", label: "Hero image alt", type: "text" },
      { name: "primary_cta_key", label: "Primary CTA key", type: "text" },
      { name: "primary_cta_label", label: "Primary CTA label", type: "text" },
      { name: "primary_cta_href", label: "Primary CTA href", type: "text" },
      { name: "secondary_cta_key", label: "Secondary CTA key", type: "text" },
      { name: "secondary_cta_label", label: "Secondary CTA label", type: "text" },
      { name: "secondary_cta_href", label: "Secondary CTA href", type: "text" },
    ],
  },
  redirects: {
    key: "redirects", label: "Redirect", pluralLabel: "Redirects", group: "site-config", endpoint: "/redirects", nameField: "old_path",
    fields: [
      { name: "old_path", label: "Old path", type: "slug", required: true, showInList: true },
      { name: "target_type", label: "Target type", type: "text", required: true, showInList: true },
      { name: "target_id", label: "Target ID", type: "text" },
      { name: "target_path", label: "Target path", type: "text", showInList: true },
      { name: "is_permanent", label: "Permanent", type: "boolean", showInList: true },
    ],
  },
  "journey-process-steps": {
    key: "journey-process-steps", label: "Journey Process Step", pluralLabel: "Journey Process Steps", group: "marketing", endpoint: "/journey-process-steps", nameField: "title",
    fields: [
      { name: "step_label", label: "Step label", type: "text", required: true, showInList: true },
      { name: "title", label: "Title", type: "text", required: true, showInList: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "detail", label: "Detail", type: "textarea", required: true },
      { name: "icon_key", label: "Icon key", type: "text", required: true },
      { name: "sort_order", label: "Sort order", type: "number", required: true, showInList: true },
    ],
  },
  "value-propositions": {
    key: "value-propositions", label: "Value Proposition", pluralLabel: "Value Propositions", group: "marketing", endpoint: "/value-propositions", nameField: "title",
    fields: [
      { name: "step_label", label: "Step label", type: "text", required: true, showInList: true },
      { name: "title", label: "Title", type: "text", required: true, showInList: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "highlight", label: "Highlight", type: "text", required: true },
      { name: "icon_key", label: "Icon key", type: "text", required: true },
      { name: "sort_order", label: "Sort order", type: "number", required: true, showInList: true },
    ],
  },
  "concierge-services": {
    key: "concierge-services", label: "Concierge Service", pluralLabel: "Concierge Services", group: "marketing", endpoint: "/concierge-services", nameField: "title",
    fields: [
      { name: "title", label: "Title", type: "text", required: true, showInList: true },
      { name: "slug", label: "Slug", type: "slug", required: true, showInList: true },
      { name: "number_label", label: "Number label", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "icon_key", label: "Icon key", type: "text", required: true },
      { name: "image_media_id", label: "Image media", type: "relation", relation: M },
      { name: "is_featured", label: "Featured", type: "boolean" },
      { name: "is_wide", label: "Wide layout", type: "boolean" },
      { name: "sort_order", label: "Sort order", type: "number", required: true, showInList: true },
    ],
  },
  "homepage-region-panels": {
    key: "homepage-region-panels", label: "Homepage Region Panel", pluralLabel: "Homepage Region Panels", group: "marketing", endpoint: "/homepage-region-panels", nameField: "title",
    fields: [
      { name: "key", label: "Key", type: "slug", required: true, showInList: true },
      { name: "label", label: "Label", type: "text", required: true, showInList: true },
      { name: "title", label: "Title", type: "text", required: true, showInList: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "highlights", label: "Highlights", type: "tags" },
      { name: "stat_text", label: "Stat text", type: "text", required: true },
      { name: "href", label: "Href", type: "text", helpText: "Optional override. By default, domestic/international panels link to /destinations?region=domestic or /destinations?region=international based on the panel key." },
      { name: "mood", label: "Mood", type: "text" },
      { name: "hero_media_id", label: "Hero media", type: "relation", relation: M },
      { name: "sort_order", label: "Sort order", type: "number", required: true, showInList: true },
      {
        name: "is_active",
        label: "Active on site",
        type: "boolean",
        showInList: true,
        listLabel: "Status",
        listToggle: true,
        helpText: "When off, this region panel is hidden on the homepage.",
      },
    ],
  },
  "about-story-sections": {
    key: "about-story-sections", label: "About Story Section", pluralLabel: "About Story Sections", group: "marketing", endpoint: "/about-story-sections", nameField: "title",
    fields: [
      { name: "title", label: "Title", type: "text", required: true, showInList: true },
      { name: "body", label: "Body", type: "textarea", required: true },
      { name: "sort_order", label: "Sort order", type: "number", required: true, showInList: true },
    ],
  },
  "homepage-promo": {
    key: "homepage-promo", label: "Homepage Promo", pluralLabel: "Homepage Promo", group: "marketing", endpoint: "/homepage-promo", isSingleton: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      {
        name: "assurances",
        label: "Assurances",
        type: "nested-list",
        nestedList: "promoAssurances",
        readFrom: (record) => nestedListToFormValue("promoAssurances", record.assurances),
        writeValue: (value) => formValueToNestedList("promoAssurances", value),
      },
    ],
  },
  "travel-expert-settings": {
    key: "travel-expert-settings", label: "Travel Expert Settings", pluralLabel: "Travel Expert Settings", group: "marketing", endpoint: "/travel-expert-settings", isSingleton: true,
    fields: [
      { name: "desk_headline", label: "Desk headline", type: "text", required: true },
      { name: "hours_label", label: "Hours label", type: "text", required: true },
      { name: "hours_value", label: "Hours value", type: "text", required: true },
      { name: "live_desk_label", label: "Live desk label", type: "text", required: true },
      { name: "live_desk_value", label: "Live desk value", type: "text", required: true },
    ],
  },
  "about-page-header": {
    key: "about-page-header", label: "About Page Header", pluralLabel: "About Page Header", group: "marketing", endpoint: "/about-page-header", isSingleton: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
    ],
  },
  "job-openings": {
    key: "job-openings", label: "Job Opening", pluralLabel: "Job Openings", group: "careers-legal", endpoint: "/job-openings", nameField: "title",
    fields: [
      { name: "title", label: "Title", type: "text", required: true, showInList: true },
      { name: "slug", label: "Slug", type: "slug", required: true, showInList: true },
      { name: "location", label: "Location", type: "text", required: true, showInList: true },
      { name: "employment_type", label: "Employment type", type: "text", required: true, showInList: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "sort_order", label: "Sort order", type: "number", required: true, showInList: true },
      { name: "is_published", label: "Published", type: "boolean" },
    ],
  },
  "careers-page-extras": {
    key: "careers-page-extras", label: "Careers Page Extras", pluralLabel: "Careers Page Extras", group: "careers-legal", endpoint: "/careers-page-extras", isSingleton: true,
    fields: [
      { name: "culture_chips", label: "Culture chips", type: "tags" },
      { name: "fallback_title", label: "Fallback title", type: "text", required: true },
      { name: "fallback_description", label: "Fallback description", type: "textarea", required: true },
    ],
  },
  "chat-agent-settings": {
    key: "chat-agent-settings", label: "Chat Agent Settings", pluralLabel: "Chat Agent Settings", group: "chat-agent", endpoint: "/chat-agent-settings", isSingleton: true,
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "role", label: "Role", type: "text", required: true },
      { name: "greeting", label: "Greeting", type: "text", required: true },
      { name: "status_text", label: "Status text", type: "text", required: true },
      { name: "avatar_media_id", label: "Avatar media", type: "relation", relation: M },
    ],
  },
  "chat-agent-welcome-messages": {
    key: "chat-agent-welcome-messages", label: "Chat Welcome Message", pluralLabel: "Chat Welcome Messages", group: "chat-agent", endpoint: "/chat-agent-welcome-messages", nameField: "message",
    fields: [
      { name: "message", label: "Message", type: "textarea", required: true, showInList: true },
      { name: "sort_order", label: "Sort order", type: "number", required: true, showInList: true },
    ],
  },
  "chat-agent-quick-replies": {
    key: "chat-agent-quick-replies", label: "Chat Quick Reply", pluralLabel: "Chat Quick Replies", group: "chat-agent", endpoint: "/chat-agent-quick-replies", nameField: "label",
    fields: [
      { name: "key", label: "Key", type: "slug", required: true, showInList: true },
      { name: "label", label: "Label", type: "text", required: true, showInList: true },
      { name: "response", label: "Response", type: "textarea", required: true },
      { name: "href", label: "Href", type: "text" },
      { name: "is_external", label: "External link", type: "boolean" },
      { name: "sort_order", label: "Sort order", type: "number", required: true, showInList: true },
    ],
  },
  "form-submissions": {
    key: "form-submissions", label: "Form Submission", pluralLabel: "Form Submissions", group: "submissions", endpoint: "/form-submissions", nameField: "form_type",
    hideCreate: true, hideDelete: true, writableFields: ["status"],
    fields: [
      { name: "form_type", label: "Form type", type: "text", readOnly: true, showInList: true },
      { name: "status", label: "Status", type: "select", required: true, showInList: true, options: [
        { value: "new", label: "New" }, { value: "read", label: "Read" }, { value: "archived", label: "Archived" },
      ]},
      { name: "name", label: "Name", type: "text", readOnly: true, showInList: true },
      { name: "email", label: "Email", type: "text", readOnly: true, showInList: true },
      { name: "phone", label: "Phone", type: "text", readOnly: true },
      { name: "payload", label: "Payload", type: "json-display", readOnly: true },
      { name: "related_itinerary_id", label: "Related itinerary", type: "relation", readOnly: true, relation: { endpoint: "/itineraries", valueKey: "id", labelKey: "title" } },
      { name: "related_hotel_id", label: "Related hotel", type: "relation", readOnly: true, relation: { endpoint: "/hotels", valueKey: "id", labelKey: "name" } },
      { name: "related_destination_id", label: "Related destination", type: "relation", readOnly: true, relation: D },
      { name: "ip_address", label: "IP address", type: "text", readOnly: true },
      { name: "user_agent", label: "User agent", type: "textarea", readOnly: true },
    ],
  },
};
